### ISSUE TITLE
Safari cannot connect to server http://127.0.0.1

### ISSUE THREAD

**Issue by sreeaurovindh** [westerlind/alfred-raindrop-search#1]
The localhost does not seem to start on my machine. I am running macOS Catalina. Is there a way to start the server?

**Comment by westerlind** [comment]
Hi

If you go to the workflow's directory in a terminal, you could start the server by running python raindrop_authserver.py

My guess is that it would not work there either, if it doesn't launch correctly from Alfred, so you will likely get some error message there instead.
Could you post the error you get here, if you get any, so I could look more into it?

**Comment by sreeaurovindh** [comment]
Thanks for the note. I am getting the following error

`python: can't open file 'raindrop_authserver.py': [Errno 2] No such file or directory`

Is there a specific place you want me to cd into?

**Comment by sreeaurovindh** [comment]
Great! After starting it manually I was able to authenticate it!. Thanks appreciate it
