### ISSUE TITLE
[BUG] broken Japanese title

### ISSUE THREAD

**Issue by qawatake** [westerlind/alfred-raindrop-search#12]
The expected title is "WSLはいいぞ", but the suggested is ↓.

[![Image from Gyazo](https://i.gyazo.com/71691a1137b6e72e2388b438a5aa1596.gif)](https://gyazo.com/71691a1137b6e72e2388b438a5aa1596)

## Environment
- workflow version: 2.0.5
- macOS version 12.1

**Comment by westerlind** [comment]
@qawatake 
That looks like some kind of text encoding issue. I will look into it!

Thanks for reporting!

**Comment by westerlind** [comment]
@qawatake 

I tried this with the site in your screenshot, and it does work in Safari and Firefox, but for some reason not in Chrome or Brave (or probably other Chromium based browsers)
<img width="979" alt="image" src="https://user-images.githubusercontent.com/944962/151843573-fd68d3a6-bf3a-4a8b-8f00-9d0f46321856.png">

I will probably be able to find a fix for this, but until then you can make it work by using Safari or Firefox, or by copying the link from the address bar, clicking outside the browser window (for example on the desktop), and then triggering the bookmark adding. If you do that, the workflow will see that you have copied a link, and that no browser is the active window, and it will then add the copied link instead, which includes fetching the title directly from the website, which also seems to work.

**Comment by qawatake** [comment]
@westerlind 

Thank you for a quick reply!
I will try to use this workflow outside the browser as you suggested until the issue is fixed.

**Comment by westerlind** [comment]
Hi @qawatake 

Sorry that this has taken such a long time, but it should finally be fixed now in version 2.0.7 that was released just now.
