### ISSUE TITLE
New raindrop account - alfred app workflow not saving to new account

### ISSUE THREAD

**Issue by ghost** [westerlind/alfred-raindrop-search#14]
Hi

I must be going mad... i removed my old Raindrop account as it was a historical mess and wanted a fresh start... what happened next is below:

#### Removal and cleansing

- removed your workflow from Alfred
- uninstalled macOS Raindrop.app
- removed all caches for Raindrop and all the directories and files for raindrop and your workflow under:
`~/Library/Caches/com.runningwithcrayons.Alfred`
- removed all profiles, caches and browser caches for Raindrop
- search the entire filesystem for any other references to raindrop or raindropio - none!

#### No errors or issues above so now re-insatll

- signed back in to new Raindrop.io account in Brave
- re-added 2.0.6 of your workflow, no issues. I can see all the directories and caches getting re-created
- When i go to add a new raindrop bookmark with the `ra ` it does not detect the new account and i never get prompted to re-authenticate no matter how mater how many times (x3) i wipe the data for raindrop and your workflow
- It is still seeing my old account for Raindrop as when i look in the `tags.json` file, the old account tags are all the tags the workflow is seeing.

Not sure where the problem is but is there a way to force removal of credentials as not finding any options in the repo?

Running macOS 12.3.1
thanks

**Comment by westerlind** [comment]
Hi @pirinoa 

I'm sorry that this is not very obvious, but what you need to do to log out of the workflow is to open the Keychain Access app, search for raindrop in the search field, and delete the entry that belongs to the Raindrop workflow (it's obvious which one it is by it's name if you see more than one)

**Comment by ghost** [comment]
Hi @westerlind 

Thank you so much... it was driving me nuts but that makes total sense now! 

Thanks for your workflow and support!
