### ISSUE TITLE
Can't recognize this site.

### ISSUE THREAD

**Issue by harisonkhlil** [westerlind/alfred-raindrop-search#15]
[异世界动漫](https://www.gqdm.net/)
`Code 1: 1151:1226: execution error: 不能将某些数据转换为预期的类型。 (-1700)`

**Comment by harisonkhlil** [comment]
And , i hope the author optimizes the recognition of Chinese, many sites have messy codes when collecting

**Comment by westerlind** [comment]
Hi @harisonkhlil 

Thanks for reporting this.
It should now be fixed, as far as I can tell, in version 2.0.7 that was just released.

Please tell me if you still experience issues with Chinese somewhare in the workflow after this fix.
