### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by misha-tgshv** [westerlind/alfred-raindrop-search#2]
Is it possible to increase the speed of loading the results?  Video — https://d.pr/v/tSgNpr

**Comment by westerlind** [comment]
There are two parts of this:

1. The search is done entirely on the server, at Raindrop.io, so the speed of the actual search could only be increased if the performance of the search at Raindrop.io itself would increase. (Or by rebuilding the search feature locally, which has other issues, and would probably lack full text search, for example)

2. As the search is initiated automatically when you type, and it might lead to other problems if the search would be initiated the exact moment a key is typed, I have used Alfreds feature for automatically determine when to send the actual search request to try to strike as good of a balance as possible. You could try to change this setting to manual values, and possibly find something that works better in your case. This setting is found if you open the settings for the workflow, double click the script filters that are green with the Raindrop logo, click the “Run Behaviour” button, and change the setting for “Queue Delay”

**Comment by misha-tgshv** [comment]
@westerlind thank you! I set 100 ms in the settings and the search became much faster.
<img src="https://d.pr/i/2YGyjH+" alt="text" width="100%" height="100%">

**Comment by DeppWang** [comment]
A good question and a good replay.
