### ISSUE TITLE
Hope to add support for Thorium

### ISSUE THREAD

**Issue by harisonkhlil** [westerlind/alfred-raindrop-search#23]
r function can be realized, but ra function can not be realized.

![CleanShot 2023-02-05 at 15 37 27@2x](https://user-images.githubusercontent.com/70578017/216807358-9aa7b95c-9832-47f2-8863-6281d3fb8ad2.png)
![CleanShot 2023-02-05 at 15 35 45@2x](https://user-images.githubusercontent.com/70578017/216807361-d7a3526f-e644-4426-a06a-5b9140dce9ab.png)

**Comment by westerlind** [comment]
Hi @harisonkhlil 

The ra feature, for adding a new bookmark to Raindrop, only works if either a web browser with a page you want to save is the top most windows, or if you have copied an address you want to save when a browser is not the top most window.

This is also what is described in the subtitle under the information about there being nothing to add, as seen in your second screenshot.

Could this be why it doesn't work, or is a browser with a page you want to save the top most window when you try "ra"?

**Comment by harisonkhlil** [comment]
As shown in the figure：
<img width="1426" alt="CleanShot 2023-02-07 at 20 30 47@2x" src="https://user-images.githubusercontent.com/70578017/217245383-b7c349e2-03ca-4a88-8589-a2c5fc871404.png">
<img width="1452" alt="CleanShot 2023-02-07 at 20 33 50@2x" src="https://user-images.githubusercontent.com/70578017/217245974-021f8ad2-d761-4a09-937f-23388cffd710.png">
