### ISSUE TITLE
URLs Failing to Open in Browser Due to URL Encoding

### ISSUE THREAD

**Issue by silverbenz** [westerlind/alfred-raindrop-search#26]
Hi,

Since the 2.0.8 update I've been having problems with some results from alfred-raindrop-search. The common thread seems to be that URLs containing query strings (ie. https://some.host.com?query=somequery) are being passed to the browser with all special characters from the "?" onwards being URL encoded.

An example:
https://supportportal.juniper.net/s/article/Junos-Software-Versions-Suggested-Releases-to-Consider-and-Evaluate?language=en_US

is passed to the browser as:
https://supportportal.juniper.net/s/article/Junos-Software-Versions-Suggested-Releases-to-Consider-and-Evaluate%3Flanguage%3Den_US

This same encoded URL fails to present the requested page on Vivaldi, Firefox and Safari.

I ran the debugger while doing the search above and all copies of the URL output by the debugger do not have the URL encoding present. Had a look in the final workflow element "Open URL" and noticed the checkboxes next to both Encoding options were checked. I've unchecked them now and re-run the above query in Alfred successfully, with the URLs being presented to the browser without the URL encoding. However, I'm concerned that the Encoding options might be needed in some circumstances.

[Edit: Should also have mentioned this is a super-useful workflow that I've been using for ages. Thank you for creating and improving it for as long as you have.]

**Comment by silverbenz** [comment]
[https://github.com/westerlind/alfred-raindrop-search/issues/18#issuecomment-1586087241](url)
This comment on a different issue also highlights the same problem.

**Comment by pressdarling** [comment]
For some reason that link didn't load correctly (it runs a search for issues created by "author:url"?), but I came here to post the same issue and workaround as linked here. https://github.com/westerlind/alfred-raindrop-search/issues/18#issuecomment-1586087241

> [https://github.com/westerlind/alfred-raindrop-search/issues/18#issuecomment-1586087241](url) This comment on a different issue also highlights the same problem.

For some reason the URL wouldn't decode correctly when I tried to automate it, so I decoded it the "hard" way (working knowledge of query string formatting).

**Comment by westerlind** [comment]
This problem should be fixed now in version 2.0.9 which is just released a moment ago.
https://github.com/westerlind/alfred-raindrop-search/releases
