### ISSUE TITLE
Error when trying to auth

### ISSUE THREAD

**Issue by mgguinne** [westerlind/alfred-raindrop-search#3]
I have downloaded the workflow and can't get past the auth section?

Warning: file_get_contents(current_selection.tmp): failed to open stream: No such file or directory in Command line code on line 3

Model Identifier: MacBookAir10,1
Memory: 8 GB
System Firmware Version: 6723.61.3
System Version: macOS 11.1 (20C69)
Kernel Version: Darwin 20.2.0
System Integrity Protection: Enabled

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/10627164/103492223-15dedf80-4e75-11eb-8c9b-6649861cedd9.png">

**Comment by westerlind** [comment]
@mgguinne Thanks for reporting!
I will look into this.

**Comment by westerlind** [comment]
@mgguinne  I'm using an M1 MacBook Air myself since a few weeks, just like you, and as far as I have been able to tell it works the exact same as on Intel Macs, so the problem is likely something else then that anyway.
Did you initiate the plugin for searching your bookmarks or for adding a new bookmark the first time, when it failed to authenticate?

**Comment by westerlind** [comment]
@mgguinne I released a new version (1.6) that might fix your problem, so could you try to update to that one and see if it works better?

**Comment by mgguinne** [comment]
> @mgguinne I'm using an M1 MacBook Air myself since a few weeks, just like you, and as far as I have been able to tell it works the exact same as on Intel Macs, so the problem is likely something else then that anyway.
> Did you initiate the plugin for searching your bookmarks or for adding a new bookmark the first time, when it failed to authenticate?

I tried to do a search and it tells me not authenticated, when I try to auth it's gives me that error

**Comment by mgguinne** [comment]
> @mgguinne I released a new version (1.6) that might fix your problem, so could you try to update to that one and see if it works better?

Thanks for being so responsive :) I give this new version a go 👍

**Comment by mgguinne** [comment]
Awesome 1.6 fixed the issue for me, it took me to the auth page. It has now logged me in with the wrong account (my personal email instead of using apple as the auth). How can I get this workflow to reset the auth please?

**Comment by westerlind** [comment]
Whoops 🙂 I had never really considered the risk of getting logged in to the wrong account, but you can log out by removing the file token.json in the workflow's directory (Right click the Raindrop.io workflow in Alfred's settings and select Open in Finder to find easily get to the correct directory)
I should probably add a more intuitive way of logging out though.

Good that the main problem is solved anyway!

**Comment by mgguinne** [comment]
Yep that worked, I did have to fiddle around with logging out in safari and log back in first with my apple ID account and then it authed correctly. Thanks heaps for help.
