### ISSUE TITLE
Error when authenticating

### ISSUE THREAD

**Issue by idr4n** [westerlind/alfred-raindrop-search#4]
Hi,

I was trying to use this workflow but when trying to authenticate I get the following error:

![image](https://user-images.githubusercontent.com/20104703/105138559-1e3a4a00-5b06-11eb-98ad-a1d19e5f11cf.png)

**Comment by westerlind** [comment]
Hi @ivanddm 

I'm trying to figure out where that error message came from.

I could be entirely wrong here, but my suspicion is that the Python version that got used for this part of the workflow is not the pre-installed Python that comes with macOS. (Python is used for one part of the workflow at the moment: the local web server that is needed for the authentication mechanism to work)

Do you know if you are using the default Python, or if you have a Python version that might have come from some third party development tool or if it is installed via for example Homebrew or something like that?

Could you run "python --version" in the terminal and see what output you get from that?

Also, which version of macOS are you using?

**Comment by idr4n** [comment]
Hi there, and thanks for your reply.

Actually, I just checked again and the problem seems to be gone by itself, I didn't do anything else but now it is working as expected.

Therefore, I don't think it was the Python version as I am using version 3.9.1 installed with homebrew as default/system python.

Thanks in any case.

Best,

Ivan

**Comment by ctbritt** [comment]
When I try to authenticate with safari, this is what I get: 
<img width="557" alt="Screen Shot 2021-04-15 at 9 04 06 AM" src="https://user-images.githubusercontent.com/4516034/114873699-8fb62b80-9dc9-11eb-959e-dc2292a1c58d.png">

**Comment by westerlind** [comment]
@ctbritt The issue you are having with the authentication looks like it probably has to do with some sort of issue with Python on your machine.
I just released version 1.7 of this workflow, and it has one change that might help with this issue, depending on exactly what is causing it (hard do tell), so try the new version and see if that helps.
