### ISSUE TITLE
order by favorites first?

### ISSUE THREAD

**Issue by jimboroberts** [westerlind/alfred-raindrop-search#5]
Hi thanks for this workflow, but is there a way to order by favourites first?
I have a lot of bookmarks from one website, but would like the main link to appear first.

**Comment by westerlind** [comment]
Hi @jimboroberts 
There is no way to do that currently, but it is a very good idea, so I will probably add support for it in a not too distant future.
Thanks for the suggestion!

**Comment by westerlind** [comment]
This feature is now implemented (commit e2eb918b43dd5e51322206c5d4683e7eb597c16e)

I will do some more testing, and possibly make some more changes to make sure everything works as good as possible, and will then release this in version 1.7 within a few days.

**Comment by westerlind** [comment]
Closing this, as version 1.7 is now released with this feature included.
