### ISSUE TITLE
Add Dissenter Browser?

### ISSUE THREAD

**Issue by TK42DAN** [westerlind/alfred-raindrop-search#6]
Awesome workflow! Really takes Raindrop, which I've struggled to like, to a whole new level. If you're taking browser requests, I'd LOVE to see Dissenter (https://dissenter.com/) added. It's based on or similar to Brave, I believe, and I find myself using it more and more. Either way, thanks again for the workflow!

**Comment by westerlind** [comment]
Hi @TK42DAN

I'm happy to hear that you like the workflow, and I hope it will not change after my response to this. Please read all of it, even if you sense that you might not like it at all after the first few words. Thanks.

Dissenter is created by the very politically driven Gab, and even as a non American who probably technically don't have a stake in American politics, after going to Gab to see what that was about, my conclusion can not be anything else than that I can not add support for this browser, as the organisation behind it is simply too far from something that I can stand for supporting.
It is not about right wing politics in itself. I agree with that sometimes, and disagree at other times, and everyone is (and should be!) free to make up there own mind about politics and political partys!
It is rather about things that sadly too often comes with right wing politics in the US these days, and that is very appearent even when just going to the front page at Gab.

I'm not against free speach in any way though, and this workflow is an open source project that you or anyone else are free to modify to add support for an extra browser or whatever else you want to add to it.

There is a lot more that I could say about this, but GitHub is supposed to be for developement and not politics, so I will end with that.

**Comment by TK42DAN** [comment]
Thanks for your reply! I can certainly appreciate your opinion and your right to it. I hope you will read all of my response, too. 😁 (Though only when you have time; I realize it’s long.)

For what it’s worth, the person/company behind it is simply a Christian who believes in our First Amendment. I have my share of differences of opinion with “him,” too, but that’s beside the point.

What is far more dangerous than a small group of foolish extremists anywhere on the spectrum are the companies who use their purchased clout to determine what can and cannot be said, and in so doing legitimize and encourage certain extremism while silencing all dissent. Add to that a media that facilitates this by shaping the narrative of the uncritical, trusting masses and you create a population that declares freedom with their lips but denies it by their lifestyle.

Freedom is a dirty business; it requires that we put in the hard work of sifting through all the dross in order to find the gold. It requires gleaning and discernment. That said, I believe it is worth it. If I wanted someone else to make all my decisions for me I’d move to China. 😉

More over, not unlike what happens under any form of prohibition, all of those “bad” things people seek to silence through censorship actually become more and more insidious as they are allowed to fester in the dark corners. The beauty of truly free speech is that it shines a purifying light on everything and so all people can see and expose evil through rational discourse.

And so we circle back: it’s actually the folks who seek to silence dissent who 1) betray their unwillingness and/or inability to justify their position through debate and so enlist the “tyranny of the 51%” (much more fascistic than anything the tiny number of extremists could ever accomplish); and 2) are guilty of sweeping what they dislike under the rug rather than deal with it, and so create the black markets, dark corners, and speakeasies that end up nurturing and spreading the worldviews they claim to hate.

Now, I am not saying any of this in an effort to get you to support that browser. It’s your own “first amendment” rights that affirm your existing freedom to do as you choose, and I’d die for that. I simply wanted to give you a brief perspective from a relatively old guy who, through lots of reading (of all sides), a couple of university degrees, and countless discussions and debates over the last thirty-plus years, has embodied or engaged with many disparate positions before finding peace and satisfaction in this Messy Light. 🙂

Ironically, it was your wise and mature request that I please read all of your response even if I don’t like the initial sound of it, that’s led us here. I know why you phrased it that way: because you know that people tend not to respond as we wish they would, especially online. That is, it’s a very messy place littered with land mines. Fortunately, in our case today, I think we’ve found that little nugget of gold.

All the best!

Dan
