### ISSUE TITLE
Browse unsorted

### ISSUE THREAD

**Issue by piersolenski** [westerlind/alfred-raindrop-search#7]
Is there a way to browse Unsorted bookmarks in the same way you can browse by Category?

**Comment by westerlind** [comment]
Hi!

Thanks for the suggestion!

It is a good idea to add this, and I will do that soon.

**Comment by piersolenski** [comment]
Awesome - thanks!

**Comment by westerlind** [comment]
I have added support for this in the testing version now!
This means that the feature is available here on GitHub (commit 939e5c03d627a9d4826c56b11a3a8ac0910d89d8), but there is no packaged or released version with these changes yet.
I will probably release a version 1.7 with this feature within a few days, but I want to test it a bit more and also probably add one ore a few more things first.

So far it works well in my testing anyway!

**Comment by westerlind** [comment]
Closing this, as version 1.7 is now released with this feature included.

**Comment by piersolenski** [comment]
Just updated and works like a charm! Thanks! ☺️
